from datetime import datetime
from Position import Position
from openpyxl import Workbook


class ErrorType:
    DOLLAR_VALUE = "DOLLAR_VALUE"
    PNL = "PNL"
    HOLDING_QTY = "HOLDING_QTY"
    OPEN_WEIGHT = "OPEN_WEIGHT"
    CLOSE_WEIGHT = "CLOSE_WEIGHT"
    EXCHANGE_RATE_OR_BASE_CURRENCY = "EXCHANGE_RATE_OR_BASE_CURRENCY"
    YESTERDAY_PRICE = "YESTERDAY_PRICE"
    TRADE_PRICE = "TRADE_PRICE"
    PRICE_OR_PCT_MOVE = "PRICE_OR_PCT_MOVE"
    EXISTING_POSITION_MISSING = "EXISTING_POSITION_MISSING"
    QUANTITY = "QUANTITY"

